apiVersion: apps/v1
kind: Deployment
metadata:
  name: onedata-app-deployment
  labels:
    app: onedata-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onedata-app
  template:
    metadata:
      labels:
        app: onedata-app
    spec:
      containers:
        - name: onedata-app
          image: harshadhaarani/onedata-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000