apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: one-data-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: onedata.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: one-data-app-service
                port:
                  number: 3000