apiVersion: v1
kind: Service
metadata:
  name: one-data-app-service
spec:
  selector:
    app: one-data-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080